# Generated by Django 4.2.11 on 2024-04-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='category',
            field=models.CharField(choices=[('', 'Все категории'), ('праздник', 'Праздник'), ('выходной', 'Выходной'), ('международный', 'Международный')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='location',
            field=models.CharField(choices=[('', 'Все местоположения'), ('город', 'Город'), ('село', 'Село'), ('деревня', 'Деревня')], default='', max_length=100),
        ),
    ]
