# Generated by Django 4.2.11 on 2024-04-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_holiday_category_alter_holiday_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='holiday',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.category'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.location'),
        ),
    ]
