# Generated by Django 4.2.11 on 2024-04-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_category_location_alter_holiday_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.location', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Праздник'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Местоположение'),
        ),
    ]
