# Generated by Django 4.2.11 on 2024-04-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_alter_category_name_alter_holiday_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='holiday',
            name='hashtags',
            field=models.ManyToManyField(to='calendar_app.hashtag', verbose_name='Хэштеги'),
        ),
    ]
