# Generated by Django 4.2.11 on 2024-04-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_hashtag_holiday_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Хэштег'),
        ),
    ]
