# Generated by Django 4.2.11 on 2024-04-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_hashtag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
