# Generated by Django 4.2.11 on 2024-04-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_holiday_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='repeat_yearly',
            field=models.BooleanField(default=False, verbose_name='Повторяется ежегодно'),
        ),
    ]
