# Generated by Django 4.2.11 on 2024-04-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_remove_holiday_date_holiday_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, to='calendar_app.hashtag', verbose_name='Хэштеги'),
        ),
    ]
